baseURL = 'https://perfectlighthousescores.com'
languageCode = 'en-us'
title = 'Perfect LightHouse Scores'
theme = 'perfecttheme'
enableRobotsTXT = true
author = 'Scott Reilly'
[Params]
    favicon = '/assets/images/favicon.svg'
    author = 'Scott Reilly'
    description = 'How to achieve perfect lighthouse scores.'